# Generated by Django 2.2.14 on 2021-03-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taz_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taz_id', models.CharField(max_length=100)),
                ('shape', models.CharField(max_length=100)),
                ('sink', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
